### ISSUE TITLE
question about the config of crowdpose

### ISSUE THREAD

**Issue by zouxuelian** [rawalkhirodkar/MIPNet#1]
Hello, I am very interested in your work. Thank you for sharing such an excellent article. I have a question about the config of crowdpose. Why  ROOT: 'data/coco/',       TEST_SET: 'val2017'  TRAIN_SET: 'train2017'?   
TEST:
  BATCH_SIZE_PER_GPU: 24

  TRAIN_SET: 'train2017'

i think 'data/coco/' is 'data/crowdpose/'; TEST_SET: 'crowdpose_val2017'  TRAIN_SET: 'crowdpose_train2017'  ，Don't know if my understanding is correct

**Comment by rawalkhirodkar** [comment]
The config files for crowdpose have the same paths as coco config.
But these are overloaded while running. Please refer [here](https://github.com/rawalkhirodkar/MIPNet/blob/main/scripts/train/baseline/crowdpose/train.sh). 

We will release a documentation along with the model weights soon!

**Comment by zouxuelian** [comment]
Thank you very much for your reply, I would like to ask, in the config
TEST:
   BATCH_SIZE_PER_GPU: 32
   COCO_BBOX_FILE: ""
Do you need to add this file in COCO_BBOX_FILE: "", 
As shown below：
COCO_BBOX_FILE:'/media/zxl/E/zxl/coco_dataset/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'
