### ISSUE TITLE
The ocpose issues and OChuman dataset

### ISSUE THREAD

**Issue by huanghao11** [rawalkhirodkar/MIPNet#12]
Hello, your work is very good, but when I tested OChuman's dataset, I found that the path in the shell file is ocpose, and what I want to teach is: 
   I changed the ocpose to ochuman according to my ideas, in the training, this problem arose,  The train_loader is missing, can you help me to solve my issues. thanks!

=> classes: ['__background__', 'person']
=> num_images: 2231
=> load 3819 samples
=> updated lr schedule is [170, 200]
training on lambda
Traceback (most recent call last):
  File "tools/lambda/train_lambda_real.py", line 280, in <module>
    main()
  File "tools/lambda/train_lambda_real.py", line 241, in main
    train_lambda(cfg, train_loader, model, criterion_lambda, criterion, optimizer, epoch,
  File "/Workspace/MIPNet-main/MIPNet-main/tools/lambda/../../lib/core/train.py", line 355, in train_lambda
    for i, (input, target_a, target_weight_a, meta_a, target_b, target_weight_b, meta_b) in enumerate(train_loader):
ValueError: not enough values to unpack (expected 7, got 4)

**Comment by huanghao11** [comment]
I have solved this issues!

**Comment by 123qwaz** [comment]
你好，想问一下这个问题是怎么解决的呢？我也出现了这个问题
