### ISSUE TITLE
how to use core/train.py/train_lambda while training?

### ISSUE THREAD

**Issue by peterpark12** [rawalkhirodkar/MIPNet#17]
Hi, I'm going to train coco based dataset with tools/lambda/train_lambda_real.py.
And it is refer to core/train.py/train_lambda, I have a question for using this function.

It occurs error in this sentence.
"for i, (input, target_a, target_weight_a, meta_a, target_b, target_weight_b, meta_b) in enumerate(train_loader):"

Exception has occurred: ValueError
not enough values to unpack (expected 7, got 4)
  File "/MIPNet/lib/core/train.py", line 384, in train_lambda
    for i, (input, target_a, target_weight_a, meta_a, target_b, target_weight_b, meta_b) in enumerate(train_loader):
  File "/MIPNet/tools/lambda/train_lambda_real.py", line 247, in main
    final_output_dir, tb_log_dir, writer_dict, print_prefix='lambda')
  File "/MIPNet/tools/lambda/train_lambda_real.py", line 286, in <module>
    main()
ValueError: not enough values to unpack (expected 7, got 4)

Where are the [target_b, target_weight_b, meta_b] come from? There are only about input and one target_a in data in train_loader.
How do I compose target_b?

**Comment by 123qwaz** [comment]
你好，我也遇到了这个问题，请问是怎么解决的呢
