### ISSUE TITLE
Question about Training

### ISSUE THREAD

**Issue by EckoTan0804** [rawalkhirodkar/MIPNet#6]
Amazing work and thanks for sharing the code!

I  have a question regarding training: in `scripts/train` there're two folders named "lambda" and "lambda_general". What is the difference between them? Which one should I use, if I want to train and reproduce the results in the paper?

Thanks in advance!

Best Regards

**Comment by rawalkhirodkar** [comment]
Please use lambda to reproduce all results for N=2.
