### ISSUE TITLE
Possible bug in train_lambda_real.py

### ISSUE THREAD

**Issue by EckoTan0804** [rawalkhirodkar/MIPNet#7]
Hi, there might be a possible bug in `train_lambda_real.py`  ([L249 - L225](https://github.com/rawalkhirodkar/MIPNet/blob/HEAD/tools/lambda/train_lambda_real.py#L249-L255)): 

In each epoch, the `perf_indicator` is directly set to `0.0`. In other words, the new best model is achieved in each epoch and the model in the last epoch will be the final best model.
However, this is likely not correct, as the best model may not always be achieved in the last epoch.

In my opinion, the `perf_indicator` should be the return value of `validate_lambda_quantitative()` in L245.

**Comment by rawalkhirodkar** [comment]
Thank you for pointing it out.
We actually save all epoch checkpoints and manually picked the best on val set using the log files.

I will fix this best_model bug soon.
