### ISSUE TITLE
Person detection results on OCHuman

### ISSUE THREAD

**Issue by EckoTan0804** [rawalkhirodkar/MIPNet#8]
Hi, 

Regarding the YOLOv3 and Faster R-CNN person detection results on OCHuman (Table 5 of the paper), are they publicly released?

Thanks in advance!

**Comment by XiyueSun** [comment]
Hello, have you got the detection results？

**Comment by rawalkhirodkar** [comment]
Please find the detection files attached.
These are generated using off-shelf FasterRCNN at https://github.com/facebookresearch/detectron2

OCHuman: [ochuman_val_test.zip](https://github.com/rawalkhirodkar/MIPNet/files/8299878/ochuman_val_test.zip)
COCO: [coco_val_test.zip](https://github.com/rawalkhirodkar/MIPNet/files/8299880/coco_val_test.zip)
