### ISSUE TITLE
Detailed Code Instructions

### ISSUE THREAD

**Issue by anas-zafar** [rawalkhirodkar/MIPNet#9]
Thanks for the amazing work. Are there any updates on Code with detailed instructions?

**Comment by whffams2** [comment]
@rawalkhirodkar

**Comment by rawalkhirodkar** [comment]
Sorry, I have been busy. Most of the stuff to train and test the models is already present in the repository.

Install: [script](https://github.com/rawalkhirodkar/MIPNet/blob/main/scripts/install.sh)
Train: [On COCO](https://github.com/rawalkhirodkar/MIPNet/blob/main/scripts/train/lambda/coco/train.sh)
Test: [On COCO](https://github.com/rawalkhirodkar/MIPNet/blob/main/scripts/test/lambda/coco/test_lambda_coco.sh)

Will compile everything in a README.
